/**
 * URL helpers for the deep-link contract:
 * - `?processName=&processVersion=` triggers auto-navigation to the instantiation form
 * - `?redirect=` controls where to land after a successful instantiation
 *
 * Kept in a plain `.js` module so the svelte/prefer-svelte-reactivity rule
 * doesn't flag URLSearchParams usage (these helpers are non-reactive).
 */

export function readTopSearch() {
    try { return window.top.location.search; } catch { return window.location.search; }
}

export function getDeepLinkProcess(search) {
    const params = new URLSearchParams((search || '').replace(/^\?/, ''));
    const processName = params.get('processName');
    const processVersion = params.get('processVersion');
    return processName && processVersion ? { processName, processVersion } : null;
}

export function getRedirect(search) {
    const params = new URLSearchParams((search || '').replace(/^\?/, ''));
    return params.get('redirect');
}

export function clearDeepLinkParamsFromTop() {
    try {
        const url = new URL(window.top.location.href);
        url.searchParams.delete('processName');
        url.searchParams.delete('processVersion');
        window.top.history.pushState({}, document.title, url.toString());
    } catch {
        // Cross-origin or no-history — silently ignore.
    }
}

/**
 * Build the query string the Bonita form iframe expects.
 *
 * Bonita's autogenerated form (community/other-pages/process-autogenerated-form/src/js/app.js)
 * reads `id` from the URL to know which process to start. Without it, the form
 * logs "Impossible to retrieve the process definition id value from the URL"
 * and the Submit button never fires the instantiation API.
 *
 * Required: id, autoInstantiate=false
 * Preserved from caller's URL: app (if present), redirect (only on deep-link path)
 */
export function buildInstantiationFormSearch(process, sourceSearch, { keepRedirect = false } = {}) {
    const source = new URLSearchParams((sourceSearch || '').replace(/^\?/, ''));
    const out = new URLSearchParams();
    if (keepRedirect && source.get('redirect')) {
        out.set('redirect', source.get('redirect'));
    }
    out.set('id', process.id);
    out.set('autoInstantiate', 'false');
    if (source.get('app')) {
        out.set('app', source.get('app'));
    }
    return `?${out.toString()}`;
}

export function buildRedirectUrl(redirect) {
    if (!redirect) return null;
    // `redirect` is an untrusted deep-link param appended to the portal resource
    // path. Restrict it to a simple relative subpath so a crafted value can't
    // become absolute (`scheme:`), protocol-relative (`//host`), root-absolute
    // (`/path`) or climb out of the intended area (`..`). Anything else is
    // rejected (caller falls through to the in-page success message).
    const isAbsoluteScheme = /^[a-z][a-z0-9+.-]*:/i.test(redirect);
    if (isAbsoluteScheme || redirect.startsWith('//') || redirect.startsWith('/') || redirect.includes('..')) {
        return null;
    }
    return window.top.location.origin + window.top.location.pathname + '../' + redirect;
}

export function getUrlContext() {
    const href = window.location.href;
    const portalIdx = href.indexOf('/portal');
    return portalIdx >= 0 ? href.substring(0, portalIdx) : window.location.origin + '/bonita';
}
